### PR TITLE
Implemented SELECT DISTINCT

### PR DESCRIPTION
**Pull request by Stratis-Dermanoutsos**
This PR references #76

### CODE REVIEW

**Review by giorgostheo — CHANGES_REQUESTED** [review]
There are no change in mdb.py which means this will not actually run. Also, all the string manipulation stuff should be done in mdb.py, not in database.py. The same way table.py gets a boolean param, database should also receive booleans not strings.

**Comment by Stratis-Dermanoutsos** [comment]
@giorgostheo I updated the code.

I put the detection logic inside *mdb.py*.

*database.py* is only responsible for passing the boolean value to *table.py* which then handles the rest.

Also, it's been tested and works as intended with order by etc.

**Review by giorgostheo — COMMENTED** [review]
Looks good. Please change target branch to develop. After that we merge.

Well done !

**Comment by Stratis-Dermanoutsos** [comment]
Done! :)

**Pull request merged**
