### PR TITLE
references #151 + #153

### PR DESCRIPTION
**Pull request by Stratis-Dermanoutsos**

### CODE REVIEW

**Comment by Stratis-Dermanoutsos** [comment]
@giorgostheo review pls.
BTW, should this go to master as it is a basic fix and not an extra feature?

**Comment by Stratis-Dermanoutsos** [comment]
@giorgostheo review pls

**Comment by giorgostheo** [comment]
Yes yes, I will review this later today...

Thanks

**Comment by giorgostheo** [comment]
From what I can see the issue that was mentioned is solved (where comp. sci. now returns results).

However, the fact that no mechanism that "bundles" whatever is in quotes is present means that the second query does not return resuts when it should. I would argue that given the whitespace, the second query look better than the first one...

image

I will create a new issue for this. 

Let me know if you would like to work on that as well (it should not be particularly hard - it will need some testing though just to make sure that it doesn't break something else) and if you want to do so in the same PR or on a separate one. Then ,depending on what you want to do, I will either close the issue now or I will wait for the fix of the next one and close them at the same time. I would prefer the second option to be honest, but it is of course up to you.

I would hesitate to put this on master (even though it should be put there) because I do not want to create more conflicts between master-develop and the many PRs that work on develop. Putting it in develop should be fine, since that branch will be push to master at some point in the (maybe near) future.

Thanks for all the effort!

**Comment by Stratis-Dermanoutsos** [comment]
Sure, I'll work on that one as well.

Should values with spaces work both with and without double quotes or just with them?

I agree it would feel weird when a value has spaces without quotes, as the interpreter should instead determine there is another condition to handle then.

**Comment by giorgostheo** [comment]
I do not think that we should force the usage of quotes (should be able to though), for a single string. However, if the value has whitespaces then the user should be forced to use quotes.

Maybe try that and if it is complicated for some reason, we can reconsider.

**Comment by Stratis-Dermanoutsos** [comment]
@giorgostheo I did this, now. So, if the value has whitespaces, the user must use quotes or an exception will be raised. If there is no whitespace, I was not sure whether I should simply remove them or keep them as part of the value, so, if you can, I'll appreciate some thoughts on this case.

Also, in the commit's description, I mentioned an issue I ran into. If there is 1 or more double quotes in the middle of the value, it is still being kept as part of the value but that can be kept as a feature or considered an exception and throw.

Eg. the value "com"p. sci" becomes com"p. sci.

Test cases so far:
- "comp. sci." -> comp. sci.
- comp.sci. -> comp.sci.
- comp. sci. -> *raises exception*
- "comp. sci. -> *raises exception*
- comp. sci." -> *raises exception*
- "comp.sci." -> "comp.sci." *(maybe change this?)*
- "comp." sci." -> comp." sci. *(possibly raise exception?)*

**Comment by Stratis-Dermanoutsos** [comment]
Edit from the above comment:

Test cases so far:

- "comp. sci." -> comp. sci.
- comp. sci. -> raises exception
- "comp. sci. -> raises exception
- comp. sci." -> raises exception
- comp.sci. -> comp.sci.
- "comp.sci." -> comp.sci.
- "comp." sci." -> comp." sci. (possibly raise exception?)

@giorgostheo I need a review on this. Depending on the answer, next commit will probably be the final one for this PR.

I am considering allowing double quotes only as prefix + suffix. Though, I am not sure whether it should not be allowed as part of a value...

**Comment by giorgostheo** [comment]
I haven't forgot about this, these days are very busy... I will get to reviewing it ASAP

**Comment by giorgostheo** [comment]
All looks good. One last question, this seems to works even if there is a value that contains a double quote. Is that expected? Maybe values should not contain double quotes anyway...

**Comment by Stratis-Dermanoutsos** [comment]
To be honest, I had no idea what to do with these values, if we should keep them or throw an exception.
So, based on the comment, Imma do the latter and not allow them.

**Comment by giorgostheo** [comment]
Maybe that's what's best. 

Will you add something that doesn't allow them to be inserted to begin with too (apart from any added exception for the where clause)?

**Comment by Stratis-Dermanoutsos** [comment]
You mean to not allow them in names and values at all other than containing values?

**Comment by giorgostheo** [comment]
To be honest maybe that is a non issue in general. Forget what I said, if you think that the current way is stable (if you are sure that a word containing a double quote can not brake a where statement that is) then maybe we just forget about it. MDB is not a production db and putting effort into such trivial stuff is pretty meaningless (I would much rather have you work on something more meaningful than that :) ).

I will take a look at it as well and try to spot any small bugs that might exist, but it is safer if both of us do it.

**Comment by Stratis-Dermanoutsos** [comment]
It is pretty simple to handle where clauses, like the example given above, so I could do just that for now, meaning:

> - "comp." sci." -> comp." sci.

should throw an exception instead. Other than that, we can leave everything else as is for now.

---

> (I would much rather have you work on something more meaningful than that :) ).

This sounds interesting

**Comment by Stratis-Dermanoutsos** [comment]
I will push a code-cleanup later today.

Too many repetitions of same code. 😅

**Comment by giorgostheo** [comment]
Please take a look at the conflicts with the latest develop push.

**Comment by Stratis-Dermanoutsos** [comment]
Done!
Thankfully, the conflicts had nothing to do with each other but I checked to make sure and everything seems to be working.

**Pull request merged**
