### PR TITLE
Add preview functionality

### PR DESCRIPTION
**Pull request by 0xCoto**
Fulfill #13.

### CODE REVIEW

**Review by giorgostheo — CHANGES_REQUESTED** [review]
Some comments:
- As far as I can tell, this needs to be run while inside the dbdata folder. Change the listdir to './dbdata' from '.' so it can be run from the miniDB dir.
- I believe it can be more easy to use if it can be run like this "python3 preview.py". So adding a "if __name__=='__main__'" with the function call inside will be helpful.
- Adding an execution parameter (python3 preview.py dirname) where dir name is either dbdata (contains dirs) or a specific db (contains pkls) and showing info for either a db (size of each table) or a dir of dbs like dbdata (size of each db) whould be nice.
- Is the pylab import necessary? I am not 100% sure but can't the rcParams be replaced by something from plt (plt.figsize or smthing like that)?

**Comment by giorgostheo** [comment]
Also changing the None arg to True/False would make it more readable imo

**Comment by 0xCoto** [comment]
> - As far as I can tell, this needs to be run while inside the dbdata folder. Change the listdir to './dbdata' from '.' so it can be run from the miniDB dir.

Done

> - I believe it can be more easy to use if it can be run like this "python3 preview.py". So adding a "if name=='main'" with the function call inside will be helpful.

Done

> - Adding an execution parameter (python3 preview.py dirname) where dir name is either dbdata (contains dirs) or a specific db (contains pkls) and showing info for either a db (size of each table) or a dir of dbs like dbdata (size of each db) whould be nice.

Done

> - Is the pylab import necessary? I am not 100% sure but can't the rcParams be replaced by something from plt (plt.figsize or smthing like that)?

yep, fixed

> Also changing the None arg to True/False would make it more readable imo

Done

**Comment by 0xCoto** [comment]
> Adding an execution parameter (python3 preview.py dirname) where dir name is either dbdata

Oops, that's not quite well-coded. Let me fix it up before you merge real quick...

**Comment by giorgostheo** [comment]
Paths are not working. Currently os.listdir finds no paths and os.walk finds no files. You need to add "dirname"/ in front of these two at least.

Afterwards run preview again in a new workspace (no sys.append etc) and make sure it works.

**Comment by 0xCoto** [comment]
Just tested - it should work now

**Review by giorgostheo — APPROVED** [review]
OK this works. 

Functionality for analyzing specific databases instead of the whole dbdata folder doesnt exist, but i will merge anyway and will add this as a separate issue.

**Pull request merged**
